import { useMemo, useState } from "react";
import Link from "next/link";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import AlbumItem from "../components/AlbumItem";
import { IAlbumItem } from "../types";

const Home: NextPage = ({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [page, setPage] = useState(1);
  const AlbumList = useMemo(() => {
    const pageAlbumList = data.slice((page - 1) * 5, page * 5);
    return (
      <div>
        <ul>
          {pageAlbumList.map((item: IAlbumItem) => (
            <AlbumItem key={item.id} item={item} />
          ))}
        </ul>
      </div>
    );
  }, [page, data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>freed Album</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>앨범</h1>
        <Link href="/album/1">페이지 1로가기</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/albums");
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
};
